export const GET_VISIONS_REQUEST = "GET_VISIONS_REQUEST";
export const GET_VISIONS_SUCCESS = "GET_VISIONS_SUCCESS";
export const GET_VISIONS_ERROR = "GET_VISIONS_ERROR";

export const ADD_VISION_REQUEST = "ADD_VISION_REQUEST";
export const ADD_VISION_SUCCESS = "ADD_VISION_SUCCESS";
export const ADD_VISION_ERROR = "ADD_VISION_ERROR";

export const UPDATE_VISION_REQUEST = "UPDATE_VISION_REQUEST";
export const UPDATE_VISION_SUCCESS = "UPDATE_VISION_SUCCESS";
export const UPDATE_VISION_ERROR = "UPDATE_VISION_ERROR";

export const DELETE_VISION_REQUEST = "DELETE_VISION_REQUEST";
export const DELETE_VISION_SUCCESS = "DELETE_VISION_SUCCESS";
export const DELETE_VISION_ERROR = "DELETE_VISION_ERROR";
